export const specialCategoriesHeaders = [
  'For students and teachers',
  'For classroom assistance',
  'For Open Source projects',
  'For universities and educational organizations',
  'For startups',
  'For training courses, coding schools, and bootcamps',
  'For former student license holders',
  'For Developer Recognition Program',
  'For non-profit organizations',
  'For user groups',
  'For users of competing tools',
  '3-month trial for teams',
  'For content creators',
  'For non-academic educators',
];
